services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./uploads:/app/uploads
    environment:
      - TZ=Asia/Tokyo
      - HUGGINGFACE_HUB_CACHE=/app/cache/huggingface
      - HF_TOKEN=${HF_TOKEN}
    env_file:
      - .env
    restart: always