version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./uploads:/app/uploads
    environment:
      - TZ=Asia/Tokyo
    restart: always
